# Generated by Django 5.0.6 on 2024-06-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name="borrowing",
            name="book",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="book",
            field=models.ManyToManyField(to="book.book"),
        ),
    ]
